### ISSUE TITLE
(driver.Pan115Client).List 问题

### ISSUE THREAD

**Issue by northsea4** [SheltonZhu/115driver#1]
## 简述
在alist里浏览，发现一个有10000个文件的目录，alist里只显示1872个文件。

## 复现
在一个空目录下，创建(上传)10000个文件。

```go
func main() {
	cr := &driver.Credential{
		UID:  "xxx",
		CID:  "xxx",
		SEID: "xxx",
	}

	client := driver.Defalut().ImportCredential(cr)
	if err := client.LoginCheck(); err != nil {
		log.Fatalf("login error: %s", err)
	}
	files, err := client.List("目录ID")
	if err != nil {
		log.Fatalf("list error: %s", err)
	}
	log.Println(len(*files))
}
```

直接执行 `go run main.go` 的话，会出现错误:
```
2022/11/08 11:20:28 list error: <html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx/1.14.0</center>
</body>
</html>: unexpected error
exit status 1
```
可能是每一次请求都添加了一次cookie？

定位在 `pkg/driver/dir.go` 的 `35` 行。

另外，这个break判断觉得可以改进一下（目前，假设总数10000，分页是2000，那最后2000就丢了）：
```go
if offset >= int64(result.Count) {
    break
}
```

## 其他
看到默认的分页大小是`56`，似乎小了一些。
115表面上最大支持1150，不过其实更大也行，比如官方的加载全部，就是limit=count的，也能请求成功。

**Comment by SheltonZhu** [comment]
cookie可能是resp的set cookie导致的，下版本修复，分页下版本将提供更多选择。

**Comment by SheltonZhu** [comment]
> "（目前，假设总数10000，分页是2000，那最后2000就丢了）"
没明白为什么最后会丢失？实际测下来似乎也没有丢失。

**Comment by SheltonZhu** [comment]
> @SheltonZhu 不好意思我对go不熟悉，上面说的并不严谨。 我是这样测试的，将分页改为2000，然后List一个有10000个文件的目录，但结果文件数量只有6000个。 如果分页改为1150，结果数量则是9250

* 如果丢失的话， 15个文件，pagesize 设置为5, 那么应该也会丢失，但是我实际测试下来并没有
* 另外115的api， 当 offset > count, 会返回offset 为 0 的数据， 所以可能是115 api 的问题
* cookie的问题，在dev分支已经修复了

**Comment by jonntd** [comment]
不分页10000个浏览器不炸么

**Comment by Bennie-CHEN** [comment]
看到大佬已经close issue了，不过其实文件显示不全的问题还是很头，希望能有解决方案🥹🙏🏼
因为115官方的默认离线路径是 /root/离线下载，所以会有很多用户默认离线在这个文件夹之后不做二次整理
比如我从16年开始用115，到现在离线下载已经有4468个子文件夹了
@SheltonZhu

**Comment by SheltonZhu** [comment]
> 看到大佬已经close issue了，不过其实文件显示不全的问题还是很头，希望能有解决方案🥹🙏🏼 因为115官方的默认离线路径是 /root/离线下载，所以会有很多用户默认离线在这个文件夹之后不做二次整理 比如我从16年开始用115，到现在离线下载已经有4468个子文件夹了 @SheltonZhu

好的，似乎楼上老哥找到解决方案了，我周末看下
