### ISSUE TITLE
9月16日，115崩溃恢复后，似乎API接口调整了。用DesktopUA无法获取目录，用BrowserUA可以挂载，但是无法秒传上传。

### ISSUE THREAD

**Issue by zengge99** [SheltonZhu/115driver#24]
9月16日，115崩溃恢复后，似乎API接口调整了。用DesktopUA无法获取目录，用BrowserUA可以挂载，但是无法秒传上传。望修复，谢谢！

**Comment by SheltonZhu** [comment]
> 9月16日，115崩溃恢复后，似乎API接口调整了。用DesktopUA无法获取目录，用BrowserUA可以挂载，但是无法秒传上传。望修复，谢谢！

目前没有开发环境，节后有时间会看下

**Comment by power721** [comment]
https://github.com/alist-org/alist/issues/7198
