### ISSUE TITLE
有关 offset 的计算

### ISSUE THREAD

**Issue by northsea4** [SheltonZhu/115driver#30]
https://github.com/SheltonZhu/115driver/blob/044d8595ba2b6a072fc7955e32650be17fcc8304/pkg/driver/dir.go#L46

目前的`offset`计算处理，即 `offset = result.offset + limit` 在一般情况下是没问题的。

但最近115更新了API，限制了最大 `limit` 为 `1150`，当指定`limit`大于`1150`时，仍然可以查询成功，但只会返回最多`1150`个文件或子目录。

所以，目前这个计算方式已不适用。

**Comment by SheltonZhu** [comment]
感谢反馈，后面有时间我看一下

**Comment by ChenyangGao** [comment]
我认为这样计算更好，就不用怕返回多少条数据
offset += length(result.data)
