### ISSUE TITLE
移除 ApiLoginCheck

### ISSUE THREAD

**Issue by ChenyangGao** [SheltonZhu/115driver#31]
在 api.go 中有这样一行

```go
     ApiLoginCheck = "https://passportapi.115.com/app/1.0/web/1.0/check/sso"
```

我经过实践检验发现，115 并不禁止同一个设备多个同时登录，但是如果调用了这个接口，反而会导致强制检查，因而导致把除了最近一次登录以外的所有cookies下线，如果仅仅是想检查cookies的有效性，不如换成

https://my.115.com/?ct=guide&ac=status

即可

**Comment by ChenyangGao** [comment]
而且做这个检查，也会导致如果挂载的115分享很多的话，重启都要半天

**Comment by SheltonZhu** [comment]
有空的时候我研究下

**Comment by ChenyangGao** [comment]
可以用app版的接口，那个暂时还没什么风控，而且app版的接口有很多变种，轮流使用可以让qps至少过百

**Comment by SheltonZhu** [comment]
> 可以用app版的接口，那个暂时还没什么风控，而且app版的接口有很多变种，轮流使用可以让qps至少过百
> 
> https://proapi.115.com/android/2.0/ufile/files
> 
> 判断是不是文件，只要看 sha1 存不存在即可
> 
> fid: 文件或目录 id pid: 目录id sha1: sha1 uppt: 创建时间 upt: 更新时间 fn: 文件名 fs: 文件大小 pc: 提取码 thumb: 缩略图，如果以 ? 开头，需要拼接 [https://imgjump.115.com${thumb}&size=0&sha1=${sha1}](https://imgjump.115.com$%7Bthumb%7D&size=0&sha1=$%7Bsha1%7D)"

具体的文档有么，比如分页参数

**Comment by ChenyangGao** [comment]
> > 可以用app版的接口，那个暂时还没什么风控，而且app版的接口有很多变种，轮流使用可以让qps至少过百
> > 
> > https://proapi.115.com/android/2.0/ufile/files
> > 
> > 判断是不是文件，只要看 sha1 存不存在即可
> > 
> > fid: 文件或目录 id pid: 目录id sha1: sha1 uppt: 创建时间 upt: 更新时间 fn: 文件名 fs: 文件大小 pc: 提取码 thumb: 缩略图，如果以 ? 开头，需要拼接 [https://imgjump.115.com${thumb}&size=0&sha1=${sha1}](https://imgjump.115.com$%7Bthumb%7D&size=0&sha1=$%7Bsha1%7D)"
> 
> 具体的文档有么，比如分页参数

参数差不多，只是返回值有些差别

**Comment by SheltonZhu** [comment]
> 在 api.go 中有这样一行
> 
> ```go
>      ApiLoginCheck = "https://passportapi.115.com/app/1.0/web/1.0/check/sso"
> ```
> 
> 我经过实践检验发现，115 并不禁止同一个设备多个同时登录，但是如果调用了这个接口，反而会导致强制检查，因而导致把除了最近一次登录以外的所有cookies下线，如果仅仅是想检查cookies的有效性，不如换成
> 
> https://my.115.com/?ct=guide&ac=status
> 
> 即可

你是怎么实验的呢，我看这两个接口表现一致，只要你通过登陆获取了新的cookie或者登出，这两个接口检测cookie都是失效的

**Comment by ChenyangGao** [comment]
> > 在 api.go 中有这样一行
> > 
> > ```go
> >      ApiLoginCheck = "https://passportapi.115.com/app/1.0/web/1.0/check/sso"
> > ```
> > 
> > 我经过实践检验发现，115 并不禁止同一个设备多个同时登录，但是如果调用了这个接口，反而会导致强制检查，因而导致把除了最近一次登录以外的所有cookies下线，如果仅仅是想检查cookies的有效性，不如换成
> > 
> > https://my.115.com/?ct=guide&ac=status
> > 
> > 即可
> 
> 你是怎么实验的呢，我看这两个接口表现一致，只要你通过登陆获取了新的cookie或者登出，这两个接口检测cookie都是失效的。
> 
> 同一个设备的同一个cookie可以多地使用，只是你获取了这个设备的新的cookie，旧的cookie才会失效

实际测验了一下，发现这个漏洞刚堵上了，大概是我在群里讲过，群里有115的人一直在看
