### ISSUE TITLE
关于 Cookie KID 为非必选项的讨论

### ISSUE THREAD

**Issue by DDSDerek** [SheltonZhu/115driver#35]
在 https://github.com/SheltonZhu/115driver/commit/6944c003d9ac6c52a90a5be8e27c39f77d0c7fb4#diff-ca5034a7254210bdc9ca0024cf69aae997e4bc14097befda1813c0cadee43fefR97 更改中，KID为 115网盘 Cookie的必选项，但是目前旧Cookie没有KID项也是可以正常使用的。

所以是否考虑兼容旧Cookie，将KID设置为非必选项？

**Comment by SheltonZhu1204** [comment]
> 在 [6944c00#diff-ca5034a7254210bdc9ca0024cf69aae997e4bc14097befda1813c0cadee43fefR97](https://github.com/SheltonZhu/115driver/commit/6944c003d9ac6c52a90a5be8e27c39f77d0c7fb4#diff-ca5034a7254210bdc9ca0024cf69aae997e4bc14097befda1813c0cadee43fefR97) 更改中，KID 为 115 网盘 Cookie 的必选项，但是目前旧 Cookie 没有 KID 项也是可以正常使用的。
> 
> 所以是否考虑兼容旧 Cookie，将 KID 设置为非必选项？

如果新的cookie复制错了，少了KID是否能生效？
如果不生效那应该不算兼容格式。

**Comment by SheltonZhu** [comment]
> 在 [6944c00#diff-ca5034a7254210bdc9ca0024cf69aae997e4bc14097befda1813c0cadee43fefR97](https://github.com/SheltonZhu/115driver/commit/6944c003d9ac6c52a90a5be8e27c39f77d0c7fb4#diff-ca5034a7254210bdc9ca0024cf69aae997e4bc14097befda1813c0cadee43fefR97) 更改中，KID为 115网盘 Cookie的必选项，但是目前旧Cookie没有KID项也是可以正常使用的。
> 
> 所以是否考虑兼容旧Cookie，将KID设置为非必选项？

如果新的 cookie 复制错了，少了 KID 是否能生效？
如果不生效那应该不算兼容格式。

应该属于为了兼容旧版还生效cookie做的一种妥协。旧的cookie会慢慢的实效。

可以不验证KID，作为一个hack
