### ISSUE TITLE
115网盘挂载被防火墙拦截问题

### ISSUE THREAD

**Issue by szhyf** [SheltonZhu/115driver#7]
Alist的115网盘驱动应该用的是大佬的驱动，感谢大佬。但使用中有个问题不知是否能解决。

使用RailDrive 以WebDav方式挂载115网盘为本地驱动器，提供给EMBY使用，扫描媒体库文件时经常发生限制访问，信息如下，貌似被当攻击拦截，信息如下：
failed get objs: failed to list objs: <title id="title">访问被拦截！</title><script>function bindall() {var requestid = "20-31-21-20230126195520-1bf4891f";if(requestid === null || requestid === ""){return;}document.getElementById("d").innerText = requestid;}</script>
<style type="text/css"> .select {float: right;margin: 10px 20px 0 0;height: 32px;line-height: 20px;font-size: 14px;width: 80px;}</style>中文English
418
您的请求疑似攻击行为！

事件ID：False alarm ID

如果您是站长，您可以前往WAF控制台进行误报屏蔽设置，让您的访问不再被拦截
<script>function changeLanguage(value) {if (value === 'zh') {changeLanguageZh();} else if (value === 'en') {changeLanguageEn();} else {changeLanguageZh();}}function changeLanguageZh() {document.getElementById("title").innerHTML = "访问被拦截！";document.getElementById("a").innerHTML = "您的请求疑似攻击行为！";document.getElementById("b").innerHTML = "如果您是站长，您可以前往WAF控制台进行误报屏蔽设置，让您的访问不再被拦截";document.getElementById("c").innerHTML = "事件ID：";}function changeLanguageEn() {document.getElementById("title").innerHTML = "The access is blocked.";document.getElementById("a").innerHTML = "Sorry, your request has been intercepted because it appears to be an attack.";document.getElementById("b").innerHTML = "If you are the webmaster, configure related parameters on the WAF console to allow your requests.";document.getElementById("c").innerHTML = "Event ID:";}var language = navigator.language || navigator.browserLanguage;if (language.indexOf('zh') > -1) {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);} else if (language.indexOf('en') > -1) {changeLanguageEn();document.getElementById("option-en").setAttribute("selected", true);} else {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);}</script>: unexpected error

**Comment by SheltonZhu** [comment]
> Alist的115网盘驱动应该用的是大佬的驱动，感谢大佬。但使用中有个问题不知是否能解决。
> 
> 使用RailDrive 以WebDav方式挂载115网盘为本地驱动器，提供给EMBY使用，扫描媒体库文件时经常发生限制访问，信息如下，貌似被当攻击拦截，信息如下： failed get objs: failed to list objs: <title id="title">访问被拦截！</title><script>function bindall() {var requestid = "20-31-21-20230126195520-1bf4891f";if(requestid === null || requestid === ""){return;}document.getElementById("d").innerText = requestid;}</script>
> 
> <style type="text/css"> .select {float: right;margin: 10px 20px 0 0;height: 32px;line-height: 20px;font-size: 14px;width: 80px;}</style>中文English
> 418 您的请求疑似攻击行为！
> 
> 事件ID：False alarm ID
> 
> 如果您是站长，您可以前往WAF控制台进行误报屏蔽设置，让您的访问不再被拦截
> 
> <script>function changeLanguage(value) {if (value === 'zh') {changeLanguageZh();} else if (value === 'en') {changeLanguageEn();} else {changeLanguageZh();}}function changeLanguageZh() {document.getElementById("title").innerHTML = "访问被拦截！";document.getElementById("a").innerHTML = "您的请求疑似攻击行为！";document.getElementById("b").innerHTML = "如果您是站长，您可以前往WAF控制台进行误报屏蔽设置，让您的访问不再被拦截";document.getElementById("c").innerHTML = "事件ID：";}function changeLanguageEn() {document.getElementById("title").innerHTML = "The access is blocked.";document.getElementById("a").innerHTML = "Sorry, your request has been intercepted because it appears to be an attack.";document.getElementById("b").innerHTML = "If you are the webmaster, configure related parameters on the WAF console to allow your requests.";document.getElementById("c").innerHTML = "Event ID:";}var language = navigator.language || navigator.browserLanguage;if (language.indexOf('zh') > -1) {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);} else if (language.indexOf('en') > -1) {changeLanguageEn();document.getElementById("option-en").setAttribute("selected", true);} else {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);}</script>: unexpected error

可能是文件数量过多，调用分页api过多导致的.因为alist是获取全部后再自己分页的，这个后续可能考虑在alist上增加分页大小参数来控制了。

**Comment by Suuwills** [comment]
@SheltonZhu 请问现在这个分页大小如何设置，每次刮削一读取文件夹就开始警报了 _(:з)∠)_
